---
title: 'Practical 3 : Visualization'
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

Shreeya Kamath
220953004
CCE C


Exercise 2.1
```{r}
#a)

 results2014 <- c(0.6215,0.2223,0.0635,0.0240,0.0067,0.0620)
 barplot(results2014)

```
```{r}
 # Data for 2014 results
results2014 <- c(0.6215, 0.2223, 0.0635, 0.0240, 0.0067, 0.0620)

# Barplot with corrected labels, colors, and axis limits
barplot(results2014,
        names.arg = c('ANC', 'DA', 'EFF', 'IFP', 'COPE', 'O.'),
        col = gray.colors(6),            # Use gray colors
        ylim = c(0, 0.7),                # Set y-axis limit from 0 to 0.7
        xlab = 'Parties',                # Label for the x-axis
        ylab = 'Votes (%)')              # Label for the y-axis

```
```{r}
#b) 
 results2009 <- c(0.6590,0.1666,0,0.0455,0.0742,0.0547)
 difference <- results2014-results2009
 barplot(difference, xlab="Parties",ylab="Difference")
```
```{r}
#Exercise 2.2

#a) The scale of X is metric. Interval scale
#b) 
goals<- c(6,24,91, 8 ,4, 25, 3, 83, 89, 34, 25, 24, 18, 6, 23,10, 28, 4, 63, 6, 60, 5, 40, 2, 22, 26, 23, 26, 44, 49, 34, 2, 33, 9, 16, 55, 23, 13, 23, 4, 8, 26, 70, 4, 6, 60, 23, 95 ,28, 49, 6, 57, 33, 56,7)
# Define the intervals
intervals <- c(0, 15, 30, 45, 60, 75, 90, 96)
# Categorize the goals data into these intervals
categories <- cut(goals, breaks = intervals, right = FALSE)
# Create the frequency table
frequency_table <- table(categories)
# Print the frequency table
print(frequency_table)
```
```{r}
#c)  
hist(goals,breaks=c(0,15,30,45,60,75,90,96))
```
```{r}
#d)
plot(density(goals,adjust=1,kernel='gaussian'))
```

```{r}
#f) i)
 plot.ecdf(goals)
```
```{r}
#f)ii)
# Assuming 'goals' is a vector of numeric values
goals <- c(10, 20, 35, 50, 65, 80, 95)

# Create the categorized goals using cut()
goals_cat <- cut(goals, breaks = c(0, 15, 30, 45, 60, 75, 90, 96),
                 labels = c("0-15", "15-30", "30-45", "45-60", "60-75", "75-90", "90-96"))

# Plot the ECDF for the original 'goals' data, not the categories
plot.ecdf(goals,
          main = "ECDF of Goals",
          xlab = "Goals",
          ylab = "ECDF",
          col = "blue", 
          lwd = 2)

# Add grid lines for better visualization
grid()

```
```{r}
#Exercise 2.6

setwd('C:\\Users\\Shreeya\\Desktop')
pizza <- read.csv('pizza_delivery.csv')
 attach(pizza)
```
```{r}
#a) 
 hist(temperature,xlab='Temperature',xlim=c(40,90),
 ylim=c(0,400),col='lightgrey',ylab='Number of deliveries')
 lines(c(65,65),c(0,400),type='l',lty=2,lwd=3)
```

```{r}
#b)
 library(ggplot2)
 p1 <- ggplot(data=pizza,aes(x=temperature))
 p2 <- p1 + 
    geom_histogram(fill='darkgrey',alpha=0.5,binwidth=2.5) + 
    scale_y_continuous('Number of deliveries')
 plot(p2)
```
```{r}
#c)
 barplot(table(driver),ylim=c(0,200),col=gray.colors(7),
 ylab='Number of deliveries', xlab='Driver',main='Title')
```
```{r}
#d)
 p3 <- qplot(driver,data=pizza,aes=('bar'),fill=day)
 p4 <- p3 + 
    scale_fill_grey() +theme_bw()
 plot(p4)

```

```{r}
#Exercise 3.10

#a) setwd('C:\\Users\\Shreeya\\Desktop')
pizza <- read.csv('pizza_delivery.csv')
 attach(pizza)
 summary(pizza[,c('time','temperature','bill','pizzas')])
```

```{r}
#b) 
 quantile(time,probs=0.99)
 quantile(temperature,probs=0.99)
```
```{r}
#c)
amdev <- function(mv){1/length(mv)*sum(abs(mv-mean(mv)))}
 amdev(temperature)
```

```{r}
#d)
 sc.time <- scale(time)
 mean(sc.time)
 var(sc.time)
```

```{r}
#e)
 boxplot(temperature,range=0)
 
```
```{r}
#e)
boxplot(time,range=0)
```
```{r}
#f)
 tc <- cut(time,breaks=seq(10,60,10))
 weighted.mean(c(15,25,35,45,55),table(tc)/sum(table(tc)))

 mean(time)
 
```
```{r}
#g)
 qqplot(time[driver=='Luigi'],time[driver=='Domenico'])

```
```{r}
#g)
 qqplot(time[driver=='Mario'],time[driver=='Salvatore'])
```

